version: "3"

services: 

    backend: 
        container_name: backend
        build: ./backend
        restart: always
        ports: 
            - "4000:4000"

    
    frontend:
        container_name: frontend
        build: ./frontend
        restart: always
        ports: 
            - "3000:3000"